### ISSUE TITLE
Environment config

### ISSUE THREAD

**Issue by caique39** [robertoachar/playground-koa-mongodb-rabbitmq#1]
No arquivo _/src/config.js_ há algum motivo para montar manualmente o objeto _config_? Talvez usar um ArrayReduce no Array _environment_ seja mais apropriado. O que você acha?

**Comment by robertoachar** [comment]
Oi @caique39, tudo bem?

Consegue mandar um exemplo? Só pra eu entender melhor o que está propondo.

**Comment by caique39** [comment]
Opa! Tudo certo, @robertoachar!

Eu pensei que poderia montar a  constante _config_ dessa forma:

```javascript
const environment = ['NODE_ENV', 'DATABASE', 'QUEUE', 'PORT'];

const config = environment.reduce((acc, key) => {
    return {
        ...acc,
       [key]: process.env[key]
    }
}, {})
```

Mas, pensando direitinho, acredito que você não faz dessa forma para não perder o _auto-complete_ do editor nas variáveis de configuração `:ˆP

**Comment by jgcmarins** [comment]
daria pra adicionar typescript como type checker só pra fazer essa inferência das consts
